#!/bin/bash

############################################################
#
#       000 - 全局变量
#
############################################################
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MYFN_LIST=
START_TIME=$(date "+%s")


############################################################
#
#       001 - 显示高亮颜色
#
#       echo_color  "信息"  "颜色"
#
############################################################
echo_color()
{
        echo -e "\e[1m\e[40;${2}m${1}\e[0m"
}


############################################################
#
#       002 - 显示高亮颜色不换行
#
#       echo_line  "信息"  "颜色"
#
############################################################
echo_line()
{
        echo -n "$(echo_color "$1" "$2")"
}


############################################################
#
#       003 - 显示成功的提示
#
#       echo_success  "信息"
#
############################################################
echo_success()
{
        echo_color "$1" "32"
}


############################################################
#
#       004 - 显示错误的提示
#
#       echo_error  "信息"
#
############################################################
echo_error()
{
        echo_color "$1" "31"
        exit 1
}


############################################################
#
#       005 - 显示警告的提示
#
#       echo_warning  "信息"
#
############################################################
echo_warning()
{
        echo_color "$1" "33"
        sleep 3
}


############################################################
#
#       006 - 显示成功的提示不换行
#
#       display_success  "信息"
#
############################################################
display_success()
{
        echo_line "Success: " "32"
        echo "$1"
}


############################################################
#
#       007 - 检查用户是否为 root
#
#       check_root
#
############################################################
check_root()
{
        if [[ "$(id -u)" != "0" ]]; then
                echo_error "Error: must run with root"
        fi
}


############################################################
#
#       008 - 计时器
#
#       time_used
#
############################################################
time_used()
{
        local END_TIME=$(date "+%s")
        local MINUTES=$(( (END_TIME - START_TIME) / 60 ))
        local SECONDS=$(( (END_TIME - START_TIME) % 60 ))
        
        echo_color "${MINUTES} minutes ${SECONDS} seconds" "34"
}


############################################################
#
#       009 - 显示成功并计时
#
#       time_success
#
############################################################
time_success()
{
        display_success "$(time_used)"
}


############################################################
#
#       010 - 调整系统时间
#
#       adjust_time
#
############################################################
adjust_time()
{
        local NUM=
        local SECONDS=
        
        if ( ping -c 1 ntp1.aliyun.com &> /dev/null ); then
                
                if ( ! type -p ntpdate &> /dev/null ); then
                        
                        for (( NUM=0; NUM < 5; NUM++ )); do
                                yum -y install ntpdate
                        done
                        
                fi
                
                systemctl stop    ntpd || true
                systemctl disable ntpd || true
                
                for (( NUM=1; NUM < 11; NUM++ )); do
                        
                        echo "adjust system time ${NUM} ..."
                        
                        SECONDS=$(ntpdate ntp1.aliyun.com | awk '{ print $(NF-1) }')
                        
                        if [[ "0" < "$SECONDS" ]] && [[ "$SECONDS" < "1" ]]; then
                                break 1
                        fi
                        
                done
                
                hwclock -w
                
        fi
}


############################################################
#
#       011 - 获取配置文件的值
#
#       config_file  "键"  "值"  "文件"
#
############################################################
config_file()
{
        local KEY="$1"
        local VALUE="$2"
        local FILE="$3"
        local LINE=
        
        if [[ -s "$FILE" ]]; then
                
                while read LINE; do
                        
                        if ( echo "$LINE" | grep -iP "^[ \t]*${KEY}[ \t]*=[ \t\"]*${VALUE}[ \t\"]*$" &> /dev/null ); then
                                
                                LINE=$(echo "$LINE" | sed "s/^[ \t]*//g" | sed "s/[ \t]*$//g")
                                LINE=$(echo "$LINE" | sed "s/[ \t]*=[ \t]*/=/g")
                                LINE=$(echo "$LINE" | sed "s/\"[ \t]*/\"/g" | sed "s/[ \t]*\"/\"/g")
                                
                                KEY=$(echo "$LINE" | cut -d= -f 1 | tr "[a-z]" "[A-Z]")
                                VALUE=$(echo "$LINE" | cut -d= -f 2-)
                                
                                LINE="${KEY}=${VALUE}"
                                
                                export "$LINE"
                                
                        fi
                        
                done < ${FILE}
                
        fi
}


############################################################
#
#       012 - 获取整数
#
#       get_number  "数字"
#
############################################################
get_number()
{
        local NUM="$1"
        
        if ( echo "$NUM" | grep "^[0-9][0-9]*$" &> /dev/null ); then
                echo "$NUM" | awk '{ print $0+0 }'
        fi
}


############################################################
#
#       013 - 获取命令的选项或参数
#
#       get_option  "命令参数的个数"  "选项或参数"  "$@"
#
############################################################

# command [ -abc | -a -b -c | --file --dir | -f a.txt -d /root | --file=a.txt --dir=/root ] [ URL1 URL2 ... ]
# command -abc -y --no -f a.txt --dir=/root URL                                     # 最多支持 7 个选项或参数

# get_option "[0-9]" "[1-9]" "$@"        # 获取倒数第几个命令参数        成功则返回该参数, 失败则报错并退出
# get_option "[0-9]" "f"     "$@"        # 获取某个无参数的短选项        成功则返回该选项, 失败则返回空值
# get_option "[0-9]" "f="    "$@"        # 获取某个短选项的参数          成功则返回该参数, 失败则返回空值
# get_option "[0-9]" "file"  "$@"        # 获取某个无参数的长选项        成功则返回该选项, 失败则返回空值
# get_option "[0-9]" "file=" "$@"        # 获取某个长选项的参数          成功则返回该参数, 失败则返回空值

get_option()
{
        # 函数的默认值或报错
        local ARG1="$1"
        local ARG2="$2"
        local ARG3="$3"
        
        if [[ -z "$ARG1" ]] || [[ -z "$ARG2" ]] || [[ -z "$ARG3" ]]; then
                echo_error "Error: ${FUNCNAME} missing operand"
        fi
        
        if (( $# > 9 )); then
                echo_error "Error: ${FUNCNAME} has too many operands"
        fi
        
        # 变量
        local COMMAND_ARGUMENT_NUMBER=$(get_number "$1")
        local OPTION_OR_ARGUMENT="$2"
        
        local CAN="$COMMAND_ARGUMENT_NUMBER"
        local OOA="$OPTION_OR_ARGUMENT"
        local OOA_TYPE=
        local OOA_NUM=
        
        local OPTION=
        local NUM=
        local NUM_MINUS=
        
        # 检测 $1, 0 <= $1 <= 命令选项的个数
        if [[ -z "$CAN" ]] || [[ "$CAN" > "$(( $#-2 ))" ]]; then
                echo_error "Error: unrecognized option ${1}"
        fi
        
        # 检测 $2 并定义 OOA_TYPE, 1 <= $2 <= $1
        if   ( echo "$OOA" | grep "^[A-Za-z]$" &> /dev/null ); then
                OOA_TYPE="short_option"
        elif ( echo "$OOA" | grep "^[A-Za-z][A-Za-z0-9][A-Za-z0-9]*$" &> /dev/null ); then
                OOA_TYPE="long_option"
        elif ( echo "$OOA" | grep "^[1-9][0-9]*$" &> /dev/null ) && (( OOA <= CAN )); then
                OOA_TYPE="command_argument"
        elif ( echo "$OOA" | grep "^[A-Za-z]=$" &> /dev/null ); then
                OOA_TYPE="short_argument"
        elif ( echo "$OOA" | grep "^[A-Za-z][A-Za-z0-9][A-Za-z0-9]*=$" &> /dev/null ); then
                OOA_TYPE="long_argument"
        else
                echo_error "Error: unrecognized option ${2}"
        fi
        
        # 区域一:    1                  ~    2
        # 区域二:    3                  ~    $(( $#-CAN ))
        # 区域三:    $(( $#-CAN+1 ))    ~    $#
        
        # 检测选项或参数
        NUM="0"
        
        for OPTION in "$@"; do
                
                NUM=$(( NUM+1 ))
                
                if [[ "$NUM" < "3" ]]; then
                        continue 1
                fi
                
                if [[ "$NUM" > "$(( $#-CAN ))" ]]; then
                        if ( echo "$OPTION" | grep "^-" &> /dev/null ); then
                                echo_error "Error: unrecognized option ${OPTION}"
                        fi
                        
                        continue 1
                fi
                
                if ( echo "$OPTION" | grep "^-" &> /dev/null ); then
                        
                        if ( ! echo "$OPTION" | grep "^-[A-Za-z][A-Za-z]*$" &> /dev/null ) \
                        && ( ! echo "$OPTION" | grep "^--[A-Za-z][A-Za-z0-9][A-Za-z0-9]*$" &> /dev/null ) \
                        && ( ! echo "$OPTION" | grep "^--[A-Za-z][A-Za-z0-9][A-Za-z0-9]*=." &> /dev/null ); then
                                
                                echo_error "Error: unrecognized option ${OPTION}"
                        fi
                        
                else
                        
                        NUM_MINUS=$(( NUM-1 ))
                        
                        if ( ! echo "${!NUM_MINUS}" | grep "^-[A-Za-z][A-Za-z]*$" &> /dev/null ); then
                                echo_error "Error: unrecognized option ${OPTION}"
                        fi
                        
                fi
                
        done
        
        # 获取命令参数
        if [[ "$OOA_TYPE" == "command_argument" ]]; then
                
                OOA_NUM=$(( $#-OOA+1 ))
                echo "${!OOA_NUM}"
                
                return 0
                
        fi
        
        #
        NUM="0"
        
        for OPTION in "$@"; do
                
                NUM=$(( NUM+1 ))
                
                if [[ "$NUM" < "3" ]] || [[ "$NUM" > "$(( $#-CAN ))" ]]; then
                        continue 1
                fi
                
                if [[ "$OOA_TYPE" == "long_option" ]] && ( echo "$OPTION" | grep "^--${OOA}$" &> /dev/null ); then
                        echo "$OPTION"
                fi
                
                if [[ "$OOA_TYPE" == "" ]]; then
                        :
                fi
                
                if [[ "$OOA_TYPE" == "" ]]; then
                        :
                fi
                
                if [[ "$OOA_TYPE" == "" ]]; then
                        :
                fi
                
        done
}


############################################################
#
#       100 - 导入函数
#
############################################################
if [[ -n "$MYFN_LIST" ]]; then
        
        for MYFN_FILE in ${MYFN_LIST}; do
                
                MYFN_PATH="/usr/local/lib/${MYFN_FILE}"
                
                if [[ -s "$MYFN_PATH" ]]; then
                        . ${MYFN_PATH}
                else
                        echo_error "Error: ${MYFN_PATH} not found"
                fi
                
        done
        
fi
