#!/bin/bash

############################################################
#
#       116 - Myud 的下载工具
#
#       myud_caw  [  -c|-a|-w  -r|-h  -d DIR  -m MD5  ]  URL
#
############################################################
#  myud_caw  [  --curl|--axel|--wget  --remove|--hold  --dir=DIR  --md5=MD5  ]  URL
myud_caw()
{
        # 定义命令参数的个数
        COMMAND_ARGUMENT_NUMBER="1"
        
        # 定义变量的初始值
        local TOOLS="curl"
        local HOLD_REMOVE="remove"
        local DIR=$(pwd)
        local MD5=
        local URL=$(command_argument1 "$@")
        local FILE=
        local HTTP=
        
        local ALL_LONG_OPTION=$(long_option "$@")
        local ALL_SHORT_OPTION=$(short_option "$@")
        
        
        
        
        
        
        
        
        
        echo $TOOLS
        echo $HOLD_REMOVE
        echo $DIR
        echo $MD5
        echo $URL
        echo $FILE
        echo $HTTP
        echo ====
        echo "$ALL_LONG_OPTION"
        echo ====
        echo "$ALL_SHORT_OPTION"
}
